-- Phase 7A-1: Exercise Library Expansion
-- Run in Supabase SQL Editor. Idempotent: ON CONFLICT (name) DO NOTHING.
-- Requires unique on name (add if missing):
CREATE UNIQUE INDEX IF NOT EXISTS exercises_name_key ON exercises (name);

INSERT INTO exercises (name, category, muscle_groups, description)
VALUES
-- Strength — Chest
('Bench Press', 'strength', '{"chest","triceps","shoulders"}', 'Barbell flat bench press'),
('Incline Bench Press', 'strength', '{"chest","triceps","shoulders"}', 'Barbell incline bench press'),
('Decline Bench Press', 'strength', '{"chest","triceps","shoulders"}', 'Barbell decline bench press'),
('Dumbbell Fly', 'strength', '{"chest"}', 'Dumbbell chest fly'),
('Cable Fly', 'strength', '{"chest"}', 'Cable chest fly'),
('Incline Dumbbell Fly', 'strength', '{"chest"}', 'Incline dumbbell chest fly'),
('Push-up', 'strength', '{"chest","triceps","shoulders","core"}', 'Bodyweight push-up'),
('Wide Push-up', 'strength', '{"chest","triceps","shoulders","core"}', 'Wide grip push-up'),
('Diamond Push-up', 'strength', '{"chest","triceps","core"}', 'Close grip diamond push-up'),
('Chest Dip', 'strength', '{"chest","triceps","shoulders"}', 'Parallel bar chest dip'),
('Pec Deck', 'strength', '{"chest"}', 'Pec deck machine fly'),
('Cable Crossover', 'strength', '{"chest"}', 'Cable crossover fly'),
-- Strength — Back
('Deadlift', 'strength', '{"back","hamstrings","glutes"}', 'Conventional barbell deadlift'),
('Romanian Deadlift', 'strength', '{"hamstrings","glutes","back"}', 'RDL with hamstring focus'),
('Sumo Deadlift', 'strength', '{"back","hamstrings","glutes","quadriceps"}', 'Wide stance sumo deadlift'),
('Pull-up', 'strength', '{"back","biceps"}', 'Bodyweight pull-up'),
('Chin-up', 'strength', '{"back","biceps"}', 'Underhand grip pull-up'),
('Assisted Pull-up', 'strength', '{"back","biceps"}', 'Assisted pull-up machine'),
('Barbell Row', 'strength', '{"back","biceps"}', 'Bent-over barbell row'),
('Dumbbell Row', 'strength', '{"back","biceps"}', 'Single-arm dumbbell row'),
('Cable Row', 'strength', '{"back","biceps"}', 'Cable row'),
('Seated Cable Row', 'strength', '{"back","biceps"}', 'Seated cable row'),
('Lat Pulldown', 'strength', '{"back","biceps"}', 'Cable lat pulldown'),
('Wide Grip Lat Pulldown', 'strength', '{"back","biceps"}', 'Wide grip lat pulldown'),
('Close Grip Lat Pulldown', 'strength', '{"back","biceps"}', 'Close grip lat pulldown'),
('T-Bar Row', 'strength', '{"back","biceps"}', 'T-bar row'),
('Face Pull', 'strength', '{"shoulders","back","rear delts"}', 'Cable face pull'),
('Straight Arm Pulldown', 'strength', '{"back","lats"}', 'Straight arm cable pulldown'),
-- Strength — Shoulders
('Overhead Press', 'strength', '{"shoulders","triceps"}', 'Standing barbell overhead press'),
('Dumbbell Shoulder Press', 'strength', '{"shoulders","triceps"}', 'Seated dumbbell shoulder press'),
('Arnold Press', 'strength', '{"shoulders","triceps"}', 'Arnold dumbbell press'),
('Lateral Raise', 'strength', '{"shoulders"}', 'Dumbbell lateral raise'),
('Front Raise', 'strength', '{"shoulders"}', 'Dumbbell front raise'),
('Rear Delt Fly', 'strength', '{"shoulders","rear delts"}', 'Rear delt fly'),
('Cable Lateral Raise', 'strength', '{"shoulders"}', 'Cable lateral raise'),
('Cable Front Raise', 'strength', '{"shoulders"}', 'Cable front raise'),
('Cable Rear Delt', 'strength', '{"shoulders","rear delts"}', 'Cable rear delt fly'),
('Upright Row', 'strength', '{"shoulders","traps","biceps"}', 'Barbell or cable upright row'),
('Shrug', 'strength', '{"traps"}', 'Barbell or dumbbell shrug'),
-- Strength — Arms
('Bicep Curl', 'strength', '{"biceps"}', 'Barbell or dumbbell bicep curl'),
('Hammer Curl', 'strength', '{"biceps","forearms"}', 'Hammer curl'),
('Incline Dumbbell Curl', 'strength', '{"biceps"}', 'Incline bench dumbbell curl'),
('Barbell Curl', 'strength', '{"biceps"}', 'Standing barbell curl'),
('Cable Curl', 'strength', '{"biceps"}', 'Cable bicep curl'),
('Concentration Curl', 'strength', '{"biceps"}', 'Concentration curl'),
('Tricep Pushdown', 'strength', '{"triceps"}', 'Cable tricep pushdown'),
('Skull Crusher', 'strength', '{"triceps"}', 'Lying tricep extension'),
('Overhead Tricep Extension', 'strength', '{"triceps"}', 'Overhead tricep extension'),
('Close Grip Bench Press', 'strength', '{"triceps","chest"}', 'Close grip bench press'),
('Tricep Kickback', 'strength', '{"triceps"}', 'Dumbbell tricep kickback'),
('Cable Tricep Extension', 'strength', '{"triceps"}', 'Cable tricep extension'),
('Dip', 'strength', '{"chest","triceps","shoulders"}', 'Parallel bar dip'),
-- Strength — Legs
('Squat', 'strength', '{"quadriceps","glutes","hamstrings"}', 'Barbell back squat'),
('Front Squat', 'strength', '{"quadriceps","glutes","core"}', 'Front rack barbell squat'),
('Goblet Squat', 'strength', '{"quadriceps","glutes","core"}', 'Goblet squat'),
('Leg Press', 'strength', '{"quadriceps","glutes","hamstrings"}', 'Machine leg press'),
('Hack Squat', 'strength', '{"quadriceps","glutes"}', 'Hack squat machine'),
('Bulgarian Split Squat', 'strength', '{"quadriceps","glutes","hamstrings"}', 'Bulgarian split squat'),
('Lunge', 'strength', '{"quadriceps","glutes","hamstrings"}', 'Stationary lunge'),
('Walking Lunge', 'strength', '{"quadriceps","glutes","hamstrings"}', 'Walking lunge'),
('Reverse Lunge', 'strength', '{"quadriceps","glutes","hamstrings"}', 'Reverse lunge'),
('Leg Extension', 'strength', '{"quadriceps"}', 'Leg extension machine'),
('Leg Curl', 'strength', '{"hamstrings"}', 'Leg curl machine'),
('Lying Leg Curl', 'strength', '{"hamstrings"}', 'Lying leg curl'),
('Calf Raise', 'strength', '{"calves"}', 'Standing calf raise'),
('Seated Calf Raise', 'strength', '{"calves"}', 'Seated calf raise'),
('Hip Thrust', 'strength', '{"glutes","hamstrings"}', 'Hip thrust'),
('Glute Bridge', 'strength', '{"glutes","core"}', 'Glute bridge'),
('Step Up', 'strength', '{"quadriceps","glutes"}', 'Step up'),
('Box Jump', 'strength', '{"legs","explosive"}', 'Plyometric box jump'),
-- Strength — Core
('Plank', 'strength', '{"core"}', 'Front plank hold'),
('Side Plank', 'strength', '{"core"}', 'Side plank hold'),
('Ab Wheel Rollout', 'strength', '{"core"}', 'Ab wheel rollout'),
('Crunch', 'strength', '{"core"}', 'Ab crunch'),
('Bicycle Crunch', 'strength', '{"core"}', 'Bicycle crunch'),
('Reverse Crunch', 'strength', '{"core"}', 'Reverse crunch'),
('Leg Raise', 'strength', '{"core"}', 'Lying or hanging leg raise'),
('Hanging Leg Raise', 'strength', '{"core"}', 'Hanging leg raise'),
('Cable Crunch', 'strength', '{"core"}', 'Cable crunch'),
('Russian Twist', 'strength', '{"core"}', 'Russian twist'),
('Woodchop', 'strength', '{"core"}', 'Cable or medicine ball woodchop'),
('Pallof Press', 'strength', '{"core"}', 'Pallof press hold'),
-- Strength — Full Body / Olympic
('Clean and Press', 'strength', '{"full body","shoulders","legs"}', 'Clean and press'),
('Power Clean', 'strength', '{"full body","legs","back"}', 'Power clean'),
('Snatch', 'strength', '{"full body","legs","shoulders"}', 'Snatch'),
('Kettlebell Swing', 'strength', '{"posterior chain","cardiovascular"}', 'Two-hand kettlebell swing'),
('Kettlebell Clean', 'strength', '{"full body"}', 'Kettlebell clean'),
('Kettlebell Snatch', 'strength', '{"full body"}', 'Kettlebell snatch'),
('Farmers Walk', 'strength', '{"full body","grip","traps"}', 'Farmers walk'),
('Sled Push', 'strength', '{"legs","full body"}', 'Pushing weighted sled'),
('Battle Ropes', 'strength', '{"shoulders","core","cardiovascular"}', 'Battle rope waves'),
('Burpee', 'strength', '{"full body","cardiovascular"}', 'Burpee'),
('Thruster', 'strength', '{"full body","legs","shoulders"}', 'Thruster'),
('Turkish Get-up', 'strength', '{"full body"}', 'Turkish get-up'),
-- Cardio
('Treadmill Run', 'cardio', '{"legs","cardiovascular"}', 'Treadmill running'),
('Treadmill Walk', 'cardio', '{"legs","cardiovascular"}', 'Treadmill walking'),
('Treadmill Incline Walk', 'cardio', '{"legs","cardiovascular"}', 'Treadmill incline walk'),
('Stationary Bike', 'cardio', '{"legs","cardiovascular"}', 'Stationary bike'),
('Assault Bike', 'cardio', '{"full body","cardiovascular"}', 'Assault bike'),
('Rowing Machine', 'cardio', '{"back","legs","cardiovascular"}', 'Rowing machine'),
('Elliptical', 'cardio', '{"legs","cardiovascular"}', 'Elliptical machine'),
('Stair Climber', 'cardio', '{"legs","cardiovascular"}', 'Stair climber'),
('Jump Rope', 'cardio', '{"legs","cardiovascular"}', 'Jump rope'),
('Running', 'cardio', '{"legs","cardiovascular"}', 'Outdoor or track running'),
('Cycling', 'cardio', '{"legs","cardiovascular"}', 'Road or indoor cycling'),
('Swimming', 'cardio', '{"full body","cardiovascular"}', 'Swimming'),
('Hiking', 'cardio', '{"legs","cardiovascular"}', 'Hiking'),
-- Flexibility
('Foam Rolling', 'flexibility', '{"full body"}', 'Self-myofascial release'),
('Static Stretch', 'flexibility', '{"full body"}', 'Held stretches'),
('Dynamic Stretch', 'flexibility', '{"full body"}', 'Dynamic stretching'),
('Yoga Flow', 'flexibility', '{"full body"}', 'Yoga flow sequence'),
('Hip Flexor Stretch', 'flexibility', '{"hip flexors"}', 'Hip flexor stretch'),
('Hamstring Stretch', 'flexibility', '{"hamstrings"}', 'Hamstring stretch'),
('Chest Stretch', 'flexibility', '{"chest"}', 'Chest stretch'),
('Shoulder Stretch', 'flexibility', '{"shoulders"}', 'Shoulder stretch'),
('Quad Stretch', 'flexibility', '{"quadriceps"}', 'Quad stretch'),
-- Sports
('Basketball', 'sports', '{"full body"}', 'Basketball'),
('Soccer', 'sports', '{"full body"}', 'Soccer'),
('Tennis', 'sports', '{"full body"}', 'Tennis'),
('Golf', 'sports', '{"full body"}', 'Golf'),
('Boxing', 'sports', '{"full body"}', 'Boxing'),
('MMA', 'sports', '{"full body"}', 'MMA'),
('Wrestling', 'sports', '{"full body"}', 'Wrestling'),
('Jiu Jitsu', 'sports', '{"full body"}', 'Jiu Jitsu'),
('Rock Climbing', 'sports', '{"full body","grip"}', 'Rock climbing'),
('Skiing', 'sports', '{"legs","full body"}', 'Skiing'),
('Snowboarding', 'sports', '{"legs","full body"}', 'Snowboarding')
ON CONFLICT (name) DO NOTHING;
